# Generated by Django 3.2.15 on 2022-08-25 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_vendingmachine_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendingmachine',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vending_machine_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
