# Generated by Django 3.2.15 on 2022-08-25 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_alter_vendingmachine_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name', 'quantity')},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='quantity',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'price', 'vending_machine')},
        ),
    ]
