# Generated by Django 3.2.15 on 2022-08-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_auto_20220825_1217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='ProductOrder',
        ),
    ]
